spring:
  application:
    name: ppla-questions-app
  cache:
    caffeine:
      spec: expireAfterWrite=30m

springdoc:
  show-actuator: true

management:
  endpoints.web.exposure.include: info, health
